@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.yummy.naraka.damagesource;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;