plugins {
    id 'multiloader-common'
    id "com.hypherionmc.modutils.modpublisher"
}

publisher {
    apiKeys {
        modrinth System.getenv("MODRINTH_TOKEN")
        curseforge System.getenv("CURSE_TOKEN")
    }

    setDebug(true)
    setModrinthID("2InS5Swi")
    setCurseID("1292603")
    setVersionType("$project.version_type")
    setChangelog(rootProject.projectDir.toPath().resolve("change.md").toFile())
    setProjectVersion("${project.name}-${minecraft_version}-${project.version}")
    setJavaVersions(List.of(JavaVersion.VERSION_25))
    setGameVersions("$project.minecraft_version")
    setDisplayName("${base.archivesName.get()}-${project.version}")
    setCurseEnvironment("both")
    setArtifact("build/libs/${base.archivesName.get()}-${project.version}.jar")
}

configurations {
    commonJava {
        canBeResolved = true
    }
    commonResources {
        canBeResolved = true
    }
}

dependencies {
    compileOnly(project(':common')) {
        def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
    commonJava project(path: ':common', configuration: 'commonJava')
    commonResources project(path: ':common', configuration: 'commonResources')
}

tasks.named('publishModrinth') {
    dependsOn('build')
}

tasks.named('publishCurseforge') {
    dependsOn('build')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}