# Project
version=1.0.0
version_type=release
group=com.yummy.naraka
java_version=25
# Common
minecraft_version=26.2
mod_id=naraka
mod_name=Naraka
mod_author=lalaalal, joachimbeen, noon414, GuEunso, Gyeon___
minecraft_version_range=[26.2, 26.3)
license=MIT
credits=
description=Adds the Herobrine boss and a variety of new weapons!
neo_form_version=26.2-1
# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.152.1+26.2
# NeoForge
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
