import com.hypherionmc.modpublisher.properties.ModLoader

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

dependencies {
    modImplementation "maven.modrinth:jade:${jade_version}+forge"
    modImplementation "me.shedaniel.cloth:cloth-config-forge:${cloth_config_version}"

    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    implementation("io.github.llamalad7:mixinextras-forge:0.5.4")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.4"))
    jarJar("io.github.llamalad7:mixinextras-forge:0.5.4")
}

legacyForge {
    version = forge_version
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('forge.enabledGameTestNamespaces', mod_id)
            ideName = "Forge ${it.name.capitalize()} ${minecraft_version} (${path})"
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file("run/${minecraft_version}"))
            programArguments.addAll '--username', "${System.getProperty("user.name")}"
        }
        data {
            data()
            gameDirectory = this.mkdir(this.file("run/data"))
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/main/generated/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            programArguments.addAll 'nogui'
            gameDirectory = this.mkdir(this.file("run/${minecraft_version}"))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

sourcesJar {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

sourceSets.main.resources {
    srcDirs 'src/main/generated'
}

publisher {
    setLoaders(ModLoader.FORGE)
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}
