plugins {
    id 'multiloader-common'
    id 'fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modCompileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation 'com.google.code.findbugs:jsr305:3.0.2'

    compileOnly "org.spongepowered:mixin:0.8.7"
    compileOnly "io.github.llamalad7:mixinextras-common:0.5.3"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.5.3"

    modCompileOnly "maven.modrinth:jade:${jade_version}+fabric"
    modCompileOnly "me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}"
}

loom {
    def aw = file("src/main/resources/${mod_id}.common.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
