modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "naraka"
version = "${version}"
displayName = "Naraka"
authors = "lalaalal, joachimbeen, noon414, GuEunso, Gyeon___"
credits = "Qiye_Duyu, h2o/aoinnman, Player_7"
description = '''${description}'''
logoFile = "naraka.png"
displayURL = "https://github.com/lalaalal/Naraka"

[[dependencies.naraka]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.naraka]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "naraka.mixins.json"

[[mixins]]
config = "naraka.mixins.neoforge.json"
