modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "naraka"
version = "${version}"
displayName = "Naraka"
authors = "lalaalal, joachimbeen, noon414, GuEunso, Gyeon___"
description = '''
This mod adds Herobrine boss, new ores, and some more powerful materials which needs vanilla ores to make.

Players can get reward from boss and make new tools with added new materials.



This mod is still WIP and there will be more contents to make out. Thank You.
'''
logoFile = "naraka.png"
displayURL = "https://github.com/lalaalal/Naraka"

[[dependencies.naraka]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.naraka]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "naraka.mixins.json"
