import com.hypherionmc.modpublisher.properties.ModLoader

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

dependencies {
    implementation "maven.modrinth:jade:${jade_version}+neoforge"
    implementation "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
}

neoForge {
    version = neoforge_version
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} ${minecraft_version} (${path})"
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file("run/${minecraft_version}"))
            programArguments.addAll '--username', "${System.getProperty("user.name")}"
        }
        data {
            data()
            gameDirectory = this.mkdir(this.file("run/data"))
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/main/generated/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            programArguments.addAll 'nogui'
            gameDirectory = this.mkdir(this.file("run/${minecraft_version}"))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources {
    srcDirs 'src/main/generated'
}

publisher {
    setLoaders(ModLoader.NEOFORGE)
}
